apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tracerlensai.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tracerlensai.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tracerlensai.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tracerlensai.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: {{ .Values.env.GOOGLE_CLOUD_PROJECT | quote }}
            - name: GOOGLE_CLOUD_REGION
              value: {{ .Values.env.GOOGLE_CLOUD_REGION | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
